### ISSUE TITLE
Fix Docker Setup

### ISSUE THREAD

**Issue by Taucher2003** [RainbowDashLabs/reputation-bot#210]
The docker setup currently looks really broken. This should be fixed.

- [x] Same JDK/JRE version for all stages (#212)
- [x] Image deployment (#240)
- [x] make docker-compose usable (#211)
- [x] Make entrypoint overridable (#213)
- [ ] Remove the oudated config template? (#249)

[More context](https://canary.discord.com/channels/853250161915985958/853262454971433001/949015334000668752) (internal)
